sudo: required

services:
  - docker

script:
- docker build -t atmosphere-builder .
- git clone --recurse-submodules https://github.com/Atmosphere-NX/Atmosphere && cd Atmosphere
- cp ../entrypoint.sh .
- docker run -it -v `pwd`:/developer atmosphere-builder > build.log
- rm -rf .git
- find ./ -type f -name ".gitignore" -exec rm -rf {} \;
- git init
- git config user.name "Silent Yang"
- git config user.email "568875138@qq.com"
- git add .
- git commit -m "update build"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:2019_02_22_1970a52

branches:
  only:
    - autobuild

env:
 global:
   - GH_REF: github.com/568875138/Atmosphere-autobuild.git
